import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  Column,
  Columns,
  Container,
  Content,
  Footer as BloomerFooter,
} from 'bloomer';
import { Link } from 'gatsby';
import React from 'react';

import { SiteMetadataProvider } from '../providers/site-metadata';

export const Footer: React.SFC = () => (
  <SiteMetadataProvider>
    {providerProps => (
      <BloomerFooter id="footer">
        <Container>
          <Content>
            <Columns isFullWidth>
              <Column>
                <Link to="/">{providerProps.siteTitle}</Link>
              </Column>
            </Columns>
            <Content isSize="small">
              <p>
                This site is generated by{' '}
                <a
                  href="https://www.gatsbyjs.org/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Gatsby
                </a>
                , a blazing fast modern site generator for React.
              </p>
              <p>
                © 2018.{' '}
                <a
                  href="https://twitter.com/cheezenaan"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  cheezenaan
                </a>
              </p>
            </Content>
            <Columns>
              <Column isSize={1}>
                <a
                  href="https://twitter.com/cheezenaan"
                  /* TODO: マウスホバー時は本来のリンク色を出したい */
                  style={{ color: 'inherit' }}
                >
                  <FontAwesomeIcon icon={['fab', 'twitter']} />
                </a>
              </Column>
              <Column isSize={1}>
                <a
                  href="http://github.com/cheezenaan"
                  style={{ color: 'inherit' }}
                >
                  <FontAwesomeIcon icon={['fab', 'github']} />
                </a>
              </Column>
            </Columns>
          </Content>
        </Container>
      </BloomerFooter>
    )}
  </SiteMetadataProvider>
);
