import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  Container,
  Content,
  Footer as BloomerFooter,
  Level,
  LevelItem,
  LevelLeft,
} from 'bloomer';
import * as React from 'react';

export const Footer: React.SFC = () => (
  <BloomerFooter id="footer">
    <Container>
      <Content isSize="small">
        <p>
          This site is generated by{' '}
          <a
            href="https://www.gatsbyjs.org/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Gatsby
          </a>
          , a blazing fast modern site generator for React.
        </p>
        <Level isMobile>
          <LevelLeft>
            <LevelItem>© 2018. cheezenaan</LevelItem>
            <LevelItem
              href="https://twitter.com/cheezenaan"
              target="_blank"
              rel="noopener noreferrer"
              /* TODO: マウスホバー時は本来のリンク色を出したい */
              style={{ color: 'inherit' }}
            >
              <FontAwesomeIcon icon={['fab', 'twitter']} />
            </LevelItem>
            <LevelItem
              href="https://github.com/cheezenaan"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: 'inherit' }}
            >
              <FontAwesomeIcon icon={['fab', 'github']} />
            </LevelItem>
          </LevelLeft>
        </Level>
      </Content>
    </Container>
  </BloomerFooter>
);
